name: bundle

on:
  push:
    branches:
      - master
    paths-ignore:
      - artifact/**
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22
      -   name: Corepack & Yarn
          run: |
              corepack enable
              corepack prepare yarn@3.4.1 --activate
              if [ -f yarn.lock ]; then
                echo "🔒 Lockfile exists, using immutable install"
                yarn install --immutable
              else
                echo "⚠️  Lockfile missing, generating..."
                yarn install
              fi
      - run: yarn build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Bundle'
      - id: autotag
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
      - if: ${{ steps.autotag.outputs.tag != '' }}
        run: git push --delete origin ${{ steps.autotag.outputs.tag }}
