name: Sync & Build EXP

on:
  schedule:
    - cron: '*/60 * * * *' # 每60分钟运行一次
  workflow_dispatch:

jobs:
  sync-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          ref: exp
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/PsionicZephyr/MagVarUpdate.git
          git fetch upstream

      - name: Compare upstream/exp with local exp
        id: diffcheck
        run: |
          git fetch upstream exp
          git diff --quiet HEAD..upstream/exp || echo "changed=yes" >> $GITHUB_OUTPUT

      - name: Configure Git identity
        if: steps.diffcheck.outputs.changed == 'yes'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream changes if needed
        if: steps.diffcheck.outputs.changed == 'yes'
        run: |
          git checkout -B exp origin/exp || git checkout -b exp
          git merge -X ours upstream/exp --allow-unrelated-histories
          echo "✅ Merged upstream changes"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Corepack & Yarn
        run: |
          corepack enable
          corepack prepare yarn@3.4.1 --activate
          yarn install --immutable

      - name: Run Build
        run: yarn build

      - name: Commit build output
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Sync & Bundle'
